cluster.name: "dangdh-cluster"
network.host: 0.0.0.0

node.name: "node_macos_192.168.1.3"
node.master: true
node.data: true
#
path.data : /usr/share/elasticsearch/data/data
path.logs : /usr/share/elasticsearch/data/logs
#
#discovery.zen.ping.unicast.hosts: ["172.16.144.138", "172.16.144.128", "172.16.144.129"]
#discovery.zen.minimum_master_nodes: 2

xpack.license.self_generated.type: basic
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
#
